{{- range $idx, $val := $.Values.validators.list }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $val }}
spec:
  type: ClusterIP
  ports:
  {{- range $.Values.services}}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
  {{- end }}
  selector:
    app: {{ $val }}
{{- end }}